version: '3.8'

networks:
  ut-network:
    driver: bridge

volumes:
  ut-data:
    driver: local

services:
  ut-nginx:
    image: nginx:1.25.3
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ut-php
    networks:
      - ut-network

  ut-mysql:
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ut-data:/var/lib/mysql
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    networks:
      - ut-network

  ut-php:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
        XDEBUG_ENABLED: "true"
    container_name: ut-php
    volumes:
      - ./:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - ut-network